DEL "iBSS.n82ap.RELEASE.dfu" /f /q
DEL "iBSS.n82ap.RELEASE.payload" /f /q
DEL "iBSS.n82ap.RELEASE.d" /f /q
DEL "iBSS.n45ap.RELEASE.dfu" /f /q
DEL "iBSS.n45ap.RELEASE-312.dfu" /f /q
DEL "iBSS.m68ap.RELEASE.dfu" /f /q
DEL "iBSS.m68ap.RELEASE.payload" /f /q 
DEL "iBSS.n45ap.RELEASE.payload" /f /q 
DEL "iBSS.n82ap.RELEASE.pwned" /f /q 
DEL "iBSS.n82ap.RELEASE-312.dfu" /f /q 
DEL "WTF.s5l8900xall.RELEASE.dfu" /f /q
DEL "itunnel.exe" /f /q
DEL "wait.img3" /f /q
DEL "dl.exe" /f /q
DEL "unzip.exe" /f /q
DEL "Resources.zip" /f /q
DEL "msvcr100d.dll" /f /q
DEL "pois0n.exe" /f /q

