'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Nan0hail.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AppleLogo_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppleLogo_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DEL &quot;iBSS.n82ap.RELEASE.dfu&quot; /f /q
        '''DEL &quot;iBSS.n82ap.RELEASE.payload&quot; /f /q
        '''DEL &quot;iBSS.n82ap.RELEASE.d&quot; /f /q
        '''DEL &quot;iBSS.n45ap.RELEASE.dfu&quot; /f /q
        '''DEL &quot;iBSS.n45ap.RELEASE-312.dfu&quot; /f /q
        '''DEL &quot;iBSS.m68ap.RELEASE.dfu&quot; /f /q
        '''DEL &quot;iBSS.m68ap.RELEASE.payload&quot; /f /q 
        '''DEL &quot;iBSS.n45ap.RELEASE.payload&quot; /f /q 
        '''DEL &quot;iBSS.n82ap.RELEASE.pwned&quot; /f /q 
        '''DEL &quot;iBSS.n82ap.RELEASE-312.dfu&quot; /f /q 
        '''DEL &quot;WTF.s5l8900xall.RELEASE.dfu&quot; /f /q
        '''DEL &quot;itunnel.exe&quot; /f /q
        '''DEL &quot;wait.img3&quot; /f /q
        '''DEL &quot;dl.exe&quot; /f /q
        '''DEL &quot;unzip.exe&quot; /f /q
        '''DEL &quot;Resour [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property cleanup() As String
            Get
                Return ResourceManager.GetString("cleanup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dfuconnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfuconnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property dl() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("dl", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itunnel() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itunnel", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property msvcr100d() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("msvcr100d", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property pois0n() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pois0n", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Resources() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Resources", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Thumbs() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Thumbs", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property unzip() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("unzip", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property wait() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("wait", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
